//Source (21.6.2018): http://johanneshuebner.com/quickcms/index.html%3Fen_parameters,24.html
export const parameters = [
    {"name":"boost", "unit": "dig", "minimum": 0.00, "maximum":37813.00, "default":1700.00, "description": "0 Hz Boost in digit. 1000 digit ~ 2.5%"},
    {"name":"fweak","unit": "Hz", "minimum": 0.00, "maximum":400.00, "default":67.00, "description": "Frequency where V/Hz reaches its peak"},
    {"name":"udcnom","unit": "V", "minimum": 0.00, "maximum":1000.00, "default":0.00, "description": "Nominal voltage for fweak and boost. fweak and boost are scaled to the actual dc voltage. 0=don't scale"},
    {"name":"fpconst","unit": "Hz", "minimum": 0.00, "maximum":400.00, "default":400.00, "description": "Frequency where slip frequency is derated to form a constant power region. Only has an effect when < fweak"},
    {"name":"fslipmin", "unit": "Hz", "minimum": 0.00, "maximum":100.00, "default":1.00, "description": "Slip frequency at minimum throttle"},
    {"name":"fslipmax", "unit": "Hz", "minimum": 0.00, "maximum":100.00, "default":3.00, "description": "Slip frequency at maximum throttle"},
    {"name":"polepairs", "unit": " ", "minimum": 1.00, "maximum":16.00, "default":2.00, "description": "Pole pairs of motor (4-pole motor: 2 pole pairs)"},
    {"name":"ampmin","unit": "%", "minimum": 0.00, "maximum":100.00, "default":50.00, "description": "Relative sine amplitude at minimum throttle"},
    {"name":"encflt","unit": " ", "minimum": 0.00, "maximum":16.00, "default":4.00, "description": "Filter constant between pulse encoder and speed calculation. Makes up for slightly uneven pulse distribution"},
    {"name":"encmode","unit": " ", "minimum": 0.00, "maximum":4.00, "default":0.00, "description": "0=single channel encoder, \n 1=quadrature encoder, \n 2=quadrature /w index pulse, \n 3=SPI (deprecated) \n 4=Resolver"},
    {"name":"fmin", "unit": "Hz", "minimum": 0.00, "maximum":400.00, "default":1.00, "description": "Below this frequency no voltage is generated"},
    {"name":"fmax", "unit": "Hz", "minimum": 0.00, "maximum":400.00, "default":200.00, "description": "At this frequency slip is commanded 0 to avoid further acceleration"},
    {"name":"numimp", "unit": "Imp/rev", "minimum": 8.00, "maximum":8192.00, "default":60.00, "description": "Pulse encoder pulses per turn"},
    {"name":"syncofs","unit": "dig", "minimum": 0.00, "maximum":65535.00, "default":0.00, "description": "Phase shift of sine wave after receiving index pulse"},
    {"name":"snsm","unit": " ", "minimum": 2.00, "maximum":3.00, "default":2.00, "description": "Motor temperature sensor. 2=KTY83, 3=KTY84"},
    {"name":"pwmfrq","unit": " ", "minimum": 0.00, "maximum":3.00, "default":2.00, "description": "PWM frequency. 0=17.6kHz, 1=8.8kHz, 2=4.4kHz, 3=2.2kHz. Needs PWM restart"},
    {"name":"pwmpol", "unit": " ", "minimum": 0.00, "maximum":1.00, "default":0.00, "description": "PWM polarity. 0=active high, 1=active low. DO NOT PLAY WITH THIS! Needs PWM restart"},
    {"name":"deadtime", "unit": "dig", "minimum": 0.00, "maximum":255.00, "default":28.00, "description": "Deadtime between highside and lowside pulse. 28=800ns, 56=1.5µs. Not always linear, consult STM32 manual. Needs PWM restart"},
    {"name":"ocurlim", "unit": "A", "minimum": -65535.00, "maximum":65535.00, "default":100.00, "description": "Hardware over current limit. RMS-current times sqrt(2) + some slack"},
    {"name":"minpulse","unit": "dig", "minimum": 0.00, "maximum":4095.00, "default":1000.00, "description": "Narrowest or widest pulse, all other mapped to full off or full on, respectively"},
    {"name":"il1gain", "unit": "dig/A", "minimum": 0.00, "maximum":4095.00, "default":4.70, "description": "Digits per A of current sensor L1"},
    {"name":"il2gain", "unit": "dig/a", "minimum": 0.00, "maximum":4095.00, "default":4.70, "description": "Digits per A of current sensor L2"},
    {"name":"udcgain", "unit": "dig/V", "minimum": 0.00, "maximum":4095.00, "default":6.15, "description": "Digits per V of DC link"},
    {"name":"udcofs","unit": "dig", "minimum": 0.00, "maximum":4095.00, "default":0.00, "description": "DC link 0V offset"},
    {"name":"udclim","unit": "V", "minimum": 0.00, "maximum":1000.00, "default":540.00, "description": "High voltage at which the PWM is shut down"},
    {"name":"udcnom","unit": "V", "minimum": 0.00, "maximum":1000.00, "default":2.00, "description": "Nominal DC bus voltage. Used for adjusting boost and fweak to actual DC link voltage. 0=no adjustment"},
    {"name":"snshs", "unit": " ", "minimum": 0.00, "maximum":1.00, "default":0.00, "description": "Heatsink temperature sensor. 0=JCurve, 1=Semikron"},
    {"name":"chargemode", "unit": " ", "minimum": 0.00, "maximum":4.00, "default":0.00, "description": "0=Off, 3=Boost, 4=Buck"},
    {"name":"chargecur", "unit": " ", "minimum": 0.00, "maximum":50.00, "default":0.00, "description": "Charge current setpoint. Boost mode: charger INPUT current. Buck mode: charger output current"},
    {"name":"chargekp","unit": " ", "minimum": 0.00, "maximum":100.00, "default":80.00, "description": "Charge controller gain. Lower if you have oscillation, raise if current set point is not met"},
    {"name":"chargeflt", "unit": " ", "minimum": 0.00, "maximum":10.00, "default":8.00, "description": "Charge current filtering. Raise if you have oscillations"},
    //{"name":"chargemax","unit": "%", "minimum": 0.00, "maximum":99.00, "default":90.00, "description": "Charge mode duty cycle limit. Especially in boost mode this makes sure you don't overvolt you IGBTs if there is no battery connected."},
    //{"name":"throtamp", "unit": "%/10ms", "minimum": 0.00, "maximum":100.00, "default":100.00, "description": "Max positive throttle slew rate"},
    {"name":"potmin", "unit": "dig", "minimum": 0.00, "maximum":4095.00, "default":0.00, "description": "Value of \"pot\" when pot isn't pressed at all"},
    {"name":"potmax", "unit": "dig", "minimum": 0.00, "maximum":4095.00, "default":4095.00, "description": "Value of \"pot\" when pot is pushed all the way in"},
    {"name":"pot2min","unit": "dig", "minimum": 0.00, "maximum":4095.00, "default":4095.00, "description": "Value of \"pot2\" when regen pot is in 0 position"},
    {"name":"pot2max","unit": "dig", "minimum": 0.00, "maximum":4095.00, "default":4095.00, "description": "Value of \"pot2\" when regen pot is in full on position"},
    {"name":"brknompedal","unit": "%", "minimum": -100.00, "maximum":0.00, "default":-50.00, "description": "Foot on break pedal regen torque"},
    {"name":"brkpedalramp", "unit": "%/10ms", "minimum": 1.00, "maximum":100.00, "default":100.00, "description": "Ramp speed when entering regen. E.g. when you set brkmax to 20% and brkpedal to -60% and brkpedalramp to 1, it will take 400ms to arrive at brake force of -60%"},
    {"name":"brknom", "unit": "%", "minimum": 0.00, "maximum":100.00, "default":30.00, "description": "Regen padel travel"},
    {"name":"brkmax", "unit": "%", "minimum": 0.00, "maximum":100.00, "default":30.00, "description": "Foot-off regen torque"},
    {"name":"brkout","unit": "%", "minimum": -100.00, "maximum":-1.00, "default":-50.00, "description": "Activate brake light output at this amount of braking force"},
    {"name":"brkrampstr", "unit": "Hz", "minimum": 0.00, "maximum":400.00, "default":10.00, "description": "Below this frequency the regen torque is reduced linearly with the frequency"},
    {"name":"idlespeed","unit": "rpm", "minimum": -100.00, "maximum":1000.00, "default":-100.00, "description": "Motor idle speed. Set to -100 to disable idle function. When idle speed controller is enabled, brake pedal must be pressed on start."},
    {"name":"idlethrotlim", "unit": "%", "minimum": 0.00, "maximum":100.00, "default":50.00, "description": "Throttle limit of idle speed controller"},
    {"name":"idlemode", "unit": " ", "minimum": 0.00, "maximum":1.00, "default":0.00, "description": "Motor idle speed mode. 0=always run idle speed controller, 1=only run it when brake pedal is released, 2=like 1 but only when cruise switch is on"},
    {"name":"speedkp", "unit": "Hz", "minimum": 0.00, "maximum":100.00, "default":1.00, "description": "Speed controller gain (Cruise and idle speed). Decrease if speed oscillates. Increase for faster load regulation"},
    {"name":"cruisemode","unit": " ", "minimum": 0.00, "maximum":1.00, "default":0.00, "description": "0=button (set when button pressed, reset with brake pedal), 1=switch (set when switched on, reset when switched off or brake pedal)"},
    {"name":"speedflt","unit": "dig", "minimum": 0.00, "maximum":16.00, "default":1.00, "description": "Filter before cruise controller"},
    {"name":"bmslimhigh","unit": "%", "minimum": 0.00, "maximum":100.00, "default":50.00, "description": "Positive throttle limit on BMS under voltage"},
    {"name":"bmslimlow", "unit": "%", "minimum": -100.00, "maximum":0.00, "default":-1.00, "description":"Regen limit on BMS over voltage"},
    {"name":"udcsw", "unit": "V", "minimum": 0.00, "maximum":1000.00, "default":330.00, "description": "Voltage at which the DC contactor is allowed to close"},
    {"name":"udcmin", "unit": "V", "minimum": 0.00, "maximum":1000.00, "default":450.00, "description": "Low voltage at which a voltage warning light comes on"},
    {"name":"udcmax","unit": "V", "minimum": 0.00, "maximum":1000.00, "default":520.00, "description": "High voltage at which a voltage warning light comes on"},
    {"name":"pwmfunc", "unit": " ", "minimum": 0.00, "maximum":2.00, "default": 0.00, "description": "Quantity that controls the PWM output. 0=tmpm, 1=tmphs, 2=speed"},
    {"name":"pwmgain","unit": "dig/C", "minimum": 0.00, "maximum":65535.00, "default":100.00, "description": "Gain of PWM output"},
    {"name":"pwmofs", "unit": "dig", "minimum": -65535.00, "maximum":65535.00, "default":0.00, "description": "Offset of PWM output, 4096=full on"},
    {"name":"fslipspnt", "unit": "Hz", "minimum": -100.00, "maximum":100.00, "default":0.00, "description": "Slip setpoint in mode 2. Written by software in mode 1"},
    {"name":"ampnom", "unit": "%", "minimum": 0.00, "maximum":100.00, "default":0.00, "description": "Nominal amplitude in mode 2. Written by software in mode 1"},
]